Ph2 webapp develop
posse-ap/gen1.5-hinatakahashi pull request #2
Opened 2021-12-18 08:41 UTC by hinatakahashi

#1

2021-12-18 10:39 UTC, Mitsuru53 commented
まずコミットメッセージが、実装した内容とかけ離れているのは良くないですね

`提出しました` というコミットメッセージから何をしようとしてどういう実装したのかがレビュワーに伝わりません

実装したコードが明確なら1行コメントでいいのでコミットメッセージを書きましょう
ex: git commit -m 'hogehoge'

実装コードが暗黙知などあってパッと見で理解できないものは複数行に分けて書くようにしましょう

2021-12-18 11:17 UTC, Mitsuru53 requested changes
何点かコメントしました、ご確認ご対応よろしくお願いします 🙏 
不要なコメントアウトや、イマイチな変数名やclass、id名が散見しますので、これらの観点は全体を通して見直していただきたいです

あと、画像は圧縮されましたか？
https://compresspng.com/ja/

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +//↓棒グラフ
`棒グラフ` だけだと一体何のデータを表現しているグラフなのかわからない気がします 💦 
学習言語グラフとか学習内容別学習時間のグラフなど何の某グラフなのかわかるようなコメントにしてください
情報量が0のコメントはノイズになります 😭

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +var ctx = document.getElementById("bargraph").getContext("2d");
[ask]ctxとは？

変数名がちょっとテキトーすぎるかもです
中身が何かわかるような変数名に変更してください

`getElementById("bargraph")`
このbargraphというidも何の棒グラフなのかわからないのでわかりやすいidに変更お願いします

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +    var myBar = new Chart(ctx, {
ネストここいらないはずです
myBarという変数名は伝わらないっす 😭

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +var ctx1 = document.getElementById("piechart1");
円グラフ１というコメント、ctx1という変数、piechart1というidそれぞれをわかりやすいコメント、変数名、idに修正お願いします

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +var piechart1= new Chart(ctx1, {
piechart1という変数名をわかりやすいものにしてください

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +var ctx2 = document.getElementById("piechart2");
ditto

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +var piechart2= new Chart(ctx2, {
ditto

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.js
> +(function() {
[ask]ここも含めて以下の即時関数をバラバラにした意図ってありますか？
https://github.com/posse-ap/gen1.5-hinatakahashi/pull/2/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R171
https://github.com/posse-ap/gen1.5-hinatakahashi/pull/2/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R178
https://github.com/posse-ap/gen1.5-hinatakahashi/pull/2/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R185

特に意図なければ1つにまとめちゃっていいかなと

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.php
> +<?php
tabだと、レビューする時にめっちゃ見辛いので、よかったらスペースに変えて欲しいです 🙏 
<img width="1860" alt="スクリーンショット 2021-12-18 20 11 37" src="https://user-images.githubusercontent.com/23156390/146638909-3af436a2-439f-49ff-8e01-3084a4945a21.png">

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.php
> +			<div class="header_div1">
header_div1というclass名が何を表しているのかわからないので、このdiv部分が何を表すのかをわかるようにclass名を修正してください

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.php
> +					<span class="dli-close"></span>
[ask]dliとは？

また、class名の統一性を出して欲しいです
ハイフンつなぎにするのか、スネークケースにするのかなどです

2021-12-18 11:17 UTC, Mitsuru53 commented on src/index.php
> +				<div class="modalcontainer">
単語はそのままくっつけると可読性落ちるので、
modal_container、modalContainer、modal-containerなどにして欲しいです

2021-12-22 08:57 UTC, hinatakahashi commented on mysql/sql/init.sql
> +-- 大元のテーブル
一日の学習時間が入るテーブルです。
学習時間、学習コンテンツのテーブルと紐付き、合計学習時間を算出するもとのテーブルとなるためこのように名付けました。

2021-12-22 11:57 UTC, hinatakahashi commented on src/index.js
> +(function() {
特に意図はないです

2021-12-22 12:16 UTC, hinatakahashi commented on src/index.php
> +					<span class="dli-close"></span>
ph1の時のコードそのままコピーしました。命名理由について記憶がないため取り急ぎ直しました。

2021-12-23 08:06 UTC, Mitsuru53 commented on mysql/sql/init.sql
> +  `time` INT NOT NULL,
最後の `,` がいらないです
エラーになりますね

2021-12-23 08:25 UTC, Mitsuru53 commented on mysql/sql/init.sql
> +COMMENT ON TABLE study IS '学習時間合計テーブル'
このコメントの追加の仕方ですが、mysqlに対応してますか？
mysql、postgres、oracleなどいろんなDBがありますが、それぞれで微妙に文法が違ったりします。
おそらくこちらはmysqlのコメントの追加の仕方ではないかなと思います。
コメントの追加をmysql用に修正し、今書いているこのコメントの書式がどのDB対応なのか念の為確認していただいてもいいですか？

2021-12-23 08:42 UTC, Mitsuru53 commented on mysql/sql/init.sql
> +  `language` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
なるほど。
studyテーブルのlanguageカラムと、study_languageテーブルのlanguageカラムでテーブル間を紐付けているということですかね？
これ例えばstudy_languageのlanguageカラムの内容を変更しないといけなくなった時、studyのテーブルの該当のlanguageカラムの内容全部修正しないといけなくなるのですが、結構めんどくないですか？

studyテーブルにはlanguageではなくlanguage_idをおいて、study_languageテーブルと紐づければ、上記のようなこともおきないのかなと思います

2021-12-23 08:42 UTC, Mitsuru53 commented on mysql/sql/init.sql
> +  `content` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
ditto

2022-01-05 04:29 UTC, hinatakahashi commented on mysql/sql/init.sql
> +COMMENT ON TABLE study IS '学習時間合計テーブル'
oracleの記述でした。
mysql用への修正完了いたしました。

2022-02-02 01:54 UTC, closed without merging